### ISSUE TITLE
Build doesn't work 

### ISSUE THREAD

**Issue by arigatodl** [omisego/sample-android#18]
# Subject of the issue

I have cloned the repo and tried to build it. But it gives an error message `Project with path ':omisego-sdk' could not be found in project ':app'.`

# Your environment 

macOS High Sierra

# Steps to reproduce

Clone the repo and run build.

# Expected behavior

It should have built successfully.

# Actual behavior

It doesn't build.

**Comment by badoualy** [comment]
Try to uncomment this line:
https://github.com/omisego/sample-android/blob/master/app/build.gradle#L40

And comment line 41

**Comment by ripzery** [comment]
We've known that's a bug. The current workaround is what the @badoualy suggested.

This issue will be fixed as soon as [the current PR](https://github.com/omisego/sample-android/pull/17/files ) is merged.
