### ISSUE TITLE
Register - HTTP ERROR

### ISSUE THREAD

**Issue by CarlosRoldanx** [omisego/sample-android#5]
# Subject of the issue
HTTP 404 error when registering

# Your environment

I did not get to register due to an error when clicking register

# Expected behavior

Register account

# Actual behavior

It does not register

**Comment by ripzery** [comment]
Hi @CarlosRoldanx,

I've already cloned and run the code from the master branch. I haven't found that problem.
Can you post an error log?

**Comment by ripzery** [comment]
I've tested and it was working fine, so I'll close this issue 🙂
